name: Discord Ania Bot Deploy

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on tags starting with 'v'
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install dependencies
        run: npm install

      - name: Copy assets
        run: npm run copy:assets

      - name: Execute deploy script
        run: sh deployPrivateFiles.sh

      - name: Build
        run: npm run build

      - name: Package code
        run: zip -r deploy.zip dist

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          ssh_private_key: ${{ secrets.PROD_SERVER_SSH }}
          port: ${{ secrets.PROD_SERVER_PORT }}
          key_format: pem

      - name: Start bot with pm2
        run: pm2 start dist/index.js --name ania

      - name: Save pm2 process list
        run: pm2 save