name: Discord Ania Bot Deploy

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on tags starting with 'v'
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install dependencies
        run: npm install

      - name: Execute deploy script
        run: sh deployPrivateFiles.sh

      - name: Copy assets
        run: npm run copy:assets

      - name: Build
        run: npm run build

      - name: Create a clean deployment directory
        run: |
          mkdir clean_deploy
          mv dist clean_deploy/
          mv deployPrivateFiles.sh clean_deploy/
          # Add other necessary files or directories to the clean_deploy directory
          mv clean_deploy/* ./
          rm -r clean_deploy

      - name: Package only the clean deployment directory
        uses: actions/upload-artifact@v2
        with:
          name: clean_deploy
          path: clean_deploy

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH }}
          port: ${{ secrets.PROD_SERVER_PORT }}
          script: |
            unzip -o clean_deploy.zip -d clean_deploy

      - name: Stop bot with pm2 if running
        run: pm2 stop ania || true

      - name: Start bot with pm2
        run: pm2 start dist/index.js --name ania

      - name: Save pm2 process list
        run: pm2 save
